<?php

namespace App\Repository;
use App\Entity\Campagne;

/**
 * CampagneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampagneRepository extends \Doctrine\ORM\EntityRepository
{
    function getAllforCompany($company){
        $query = $this->createQueryBuilder('p')
            ->where('p.company = :company')
            ->setParameter('company', $company)
            ->orderBy('p.name', 'DESC')
            ->getQuery();

        return $query->getResult();
    }

    function getAllAndNullforCompany($company){
        $res = $this->getAllforCompany($company);
        
        return $res;
    }

    function findOrCreate($company, $name){
        $em = $this->getEntityManager();
        $campagne = $query = $this->createQueryBuilder('p')
         ->where('p.company = :company')
         ->andWhere('p.name = :name')
         ->setParameter('company', $company)
         ->setParameter('name', $name)
         ->getQuery()->getOneOrNullResult();
        if($campagne){
            return $campagne;
        }
        $campagne = new Campagne();
        $campagne->name = $name;
        $campagne->company = $company;
        $em->persist($campagne);
        $em->flush();
        return $campagne;
    }

    function createCurrentCampagne($company){
        $this->findOrCreate($company, "2018/2019");
    }

    function getPrevious($campagne){
        $all = $this->getAllforCompany($campagne->company);
        $found = false;
        foreach ($all as $c) {
            if ($found) {
                return $c;
            }
            if ($c->id == $campagne->id) {
                $found = true;
            }
        }
        return null;
    }

}
